name: Release logazer

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    if: github.event_name == 'push' || github.event.pull_request.draft != 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: cargo build --release

      - name: Archive exe
        run: |
          mkdir dist
          cp target/release/logazer.exe dist/logazer.exe
          7z a logazer-windows-x64.zip dist/*
          echo "ASSET=logazer-windows-x64.zip" >> $env:GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ASSET }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
